spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:dcbapp
    password: password
  h2:
    console:
      enabled: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

welcome:
  message: Welcome to Loopy

file:
  audio_path: /Users/savannahwang/Downloads/Loopy/loopy-plugins/src/main/resources/static/audio
